---
- set_fact:
    update_cache: true

- block:
  - name: "Test if package {{ package_name }} is already installed"
    command: rpm -q {{ package_name }}
    args:
      warn: no
    register: rpm_info
    changed_when: rpm_info.failed
  rescue:

  - name: "If package {{ package_name }} is missing, install package using yum."
    set_fact:
      packages_to_install: "{{ packages_to_install }},{{ package_name }}"
    when: rpm_info.failed and packages_to_install != ""

  - name: "If package {{ package_name }} is missing, install package using yum."
    set_fact:
      packages_to_install: "{{ package_name }}"
    when: rpm_info.failed and packages_to_install == ""
